# ->->->->-> Primary <-<-<-<-<-
arch: "ResNet18"
exp_name: "temp"
result_dir: "./trained_models"
num_classes: 200
exp_mode: "pretrain"
layer_type: "subnet"
init_type: "kaiming_normal"


# ->->->->-> Pruning <-<-<-<-<-
k: 1.0

# ->->->->-> Train <-<-<-<-<-
trainer: "drt"
epochs: 90
optimizer: "sgd"
lr: 0.1
lr_schedule: "step"
lr_step: 30
wd: 0.0001
momentum: 0.9

# ->->->->-> Eval <-<-<-<-<-
val_method: base


# ->->->->-> Dataset <-<-<-<-<-
dataset: TinyImageNet
batch_size: 256
test_batch_size: 256
data_dir: "/scratch/bbkc/chenhui/tiny-imagenet/tiny-imagenet-200"
data_fraction: 1.0
image_dim: 64
mean: !!python/tuple [0.4802, 0.4481, 0.3975]
std: !!python/tuple [0.2302, 0.2265, 0.2262]

# ->->->->-> Adv <-<-<-<-<-
epsilon: 0.0156 #(4/255)
num_steps: 10
step_size: 0.00392 #(1/255)
distance: "l_inf"
beta: 6.0

n_repeats: 4



# ->->->->-> Misc <-<-<-<-<-
gpu: "0,1,2,3"
seed: 1234
print_freq: 10
